package com.parkio.auth.application.durable;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.HexFormat;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

/**
 * The cross-language fixtures in {@code src/test/resources/durable-erasure-evidence/v2},
 * generated by {@code scripts/generate-durable-erasure-evidence-fixtures.py} from the Python
 * persist protocol and checked by {@code scripts/test-durable-erasure-evidence-interop.py}.
 */
final class DurableEvidenceFixtures {

    static final ObjectMapper JSON = new ObjectMapper();
    static final Path ROOT = root();

    private DurableEvidenceFixtures() {
    }

    static JsonNode json(String relative) {
        try {
            return JSON.readTree(ROOT.resolve(relative).toFile());
        } catch (IOException ex) {
            throw new UncheckedIOException(ex);
        }
    }

    static byte[] bytes(String relative) {
        try {
            return Files.readAllBytes(ROOT.resolve(relative));
        } catch (IOException ex) {
            throw new UncheckedIOException(ex);
        }
    }

    static JsonNode producer() {
        return json("producer.json");
    }

    /** The committed secret of fixture key {@code keyId} (synthetic, test-only). */
    static byte[] secret(String keyId) {
        for (JsonNode key : producer().path("keys")) {
            if (keyId.equals(key.path("keyId").asText())) {
                return HexFormat.of().parseHex(key.path("keyHex").asText());
            }
        }
        throw new IllegalArgumentException("no fixture key " + keyId);
    }

    /** The key the reference producer signs the standard cases with. */
    static TrustedKey signingKey() {
        return TrustedKey.active("interop-fixture-key-2026a", "interop-fixture-producer",
                secret("interop-fixture-key-2026a"), Instant.parse("2026-01-01T00:00:00Z"));
    }

    /** A case's trust: metadata from its expected.json, secrets from producer.json. */
    static EvidenceTrust trust(JsonNode expected) {
        List<TrustedKey> keys = new java.util.ArrayList<>();
        for (JsonNode key : expected.path("trust").path("keys")) {
            String keyId = key.path("keyId").asText();
            keys.add(new TrustedKey(keyId, key.path("producerId").asText(), secret(keyId),
                    Instant.parse(key.path("notBefore").asText()),
                    key.path("notAfter").isNull() ? null : Instant.parse(key.path("notAfter").asText()),
                    key.path("retired").asBoolean()));
        }
        return new EvidenceTrust(expected.path("trust").path("databaseIdentity").asText(), keys);
    }

    static List<String> caseNames() {
        return Stream.of(json("cases.json")).flatMap(node -> {
            List<String> names = new java.util.ArrayList<>();
            node.forEach(name -> names.add(name.asText()));
            return names.stream();
        }).toList();
    }

    /** A case's store directory as evidence objects, keyed by relative path. */
    static EvidenceObjects store(String caseName) {
        Path store = ROOT.resolve("cases").resolve(caseName).resolve("store");
        return new EvidenceObjects() {
            @Override
            public List<String> list(String prefix) {
                try (Stream<Path> files = Files.walk(store)) {
                    return files.filter(Files::isRegularFile)
                            .map(path -> store.relativize(path).toString().replace('\\', '/'))
                            .filter(key -> key.startsWith(prefix))
                            .sorted()
                            .toList();
                } catch (IOException ex) {
                    throw new UncheckedIOException(ex);
                }
            }

            @Override
            public Optional<byte[]> find(String key) {
                Path path = store.resolve(key);
                if (!Files.isRegularFile(path)) {
                    return Optional.empty();
                }
                try {
                    return Optional.of(Files.readAllBytes(path));
                } catch (IOException ex) {
                    throw new UncheckedIOException(ex);
                }
            }
        };
    }

    private static Path root() {
        URL url = DurableEvidenceFixtures.class.getClassLoader().getResource("durable-erasure-evidence/v2/cases.json");
        if (url == null) {
            throw new IllegalStateException("durable-erasure-evidence/v2 fixtures are not on the test classpath");
        }
        try {
            return Path.of(url.toURI()).getParent();
        } catch (URISyntaxException ex) {
            throw new IllegalStateException(ex);
        }
    }
}
