spring:
  application:
    name: analytics-service

server:
  port: ${SERVER_PORT:8089}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: analytics-service
    description: Parkio analytics-service
