package com.parkio.parking.calibration;

public enum CalibrationReadinessStatus {
    INSUFFICIENT_DATA,
    OPERATIONALLY_UNVERIFIED,
    CALIBRATION_INCOMPLETE,
    REGRESSION_DETECTED,
    FAIRNESS_REVIEW_REQUIRED,
    PRIVACY_REVIEW_REQUIRED,
    READY_FOR_SHADOW_EXPANSION,
    READY_FOR_CONTROLLED_CANARY_REVIEW,
    NOT_READY,
    INCONCLUSIVE,
    STABLE
}