[SERVICE]
    Flush                     1
    Daemon                    Off
    Log_Level                 ${PARKIO_NR_LOG_FLUENT_LOG_LEVEL}
    HTTP_Server               On
    HTTP_Listen               0.0.0.0
    HTTP_Port                 2020
    Health_Check              On
    HC_Errors_Count           3
    HC_Retry_Failure_Count    3
    HC_Period                 30
    scheduler.base            1
    scheduler.cap             30
    storage.path              /var/fluent-bit/state
    storage.sync              full
    storage.checksum          on
    storage.max_chunks_up     2
    storage.backlog.mem_limit 5M
    storage.metrics           on
    Parsers_File              /fluent-bit/etc/parkio/parsers.conf

[INPUT]
    Name                tail
    Tag                 parkio.pilot
    Path                /var/log/parkio-pilot/*/*-json.log
    Path_Key            pilot_path
    DB                  /var/fluent-bit/state/pilot-tail.db
    DB.Sync             Normal
    storage.type        filesystem
    Buffer_Chunk_Size   64k
    Buffer_Max_Size     256k
    Skip_Long_Lines     On
    Skip_Empty_Lines    On
    Refresh_Interval    1
    Rotate_Wait         10
    Read_from_Head      Off
    multiline.parser    parkio_docker_spring

[FILTER]
    Name                lua
    Match               parkio.pilot
    script              /fluent-bit/etc/parkio/parkio_filters.lua
    call                process_record
    protected_mode      true

[FILTER]
    Name                record_modifier
    Match               parkio.pilot
    Record              environment ${PARKIO_ENVIRONMENT}
    Record              release_id ${PARKIO_RELEASE_ID}
    Record              collector_source_sha ${PARKIO_COLLECTOR_SOURCE_SHA}
    Record              pipeline nr-log-pilot
    Record              schema_version ops.log.v1
    Record              collector ${PARKIO_NR_COLLECTOR_ID}
    Record              logtype parkio-ops

[OUTPUT]
    Name                nrlogs
    Match               parkio.pilot
    Base_URI            ${PARKIO_NR_LOG_BASE_URI}
    License_Key         ${PARKIO_NR_LOG_API_KEY}
    Compress            gzip
    tls                 Off
    Retry_Limit         False
    workers             1
    storage.total_limit_size 20M
