package com.parkio.parking.outcome;

/** Bounded explanation codes for outcome validation. */
public enum OutcomeReason {

    NOT_YET_PUBLISHED,
    VALIDATION_WINDOW_OPEN,
    COMMUNITY_CLAIM_CONFIRMED,
    MULTIPLE_AVAILABLE_VERIFICATIONS,
    SINGLE_AVAILABLE_VERIFICATION,
    COMMUNITY_FILLED_REPORTS,
    NEGATIVE_VERIFICATION,
    MODERATOR_REJECTION,
    AI_REJECTION,
    REVIEW_FAILED,
    TIME_EXPIRED,
    TIME_EXPIRED_NO_EVIDENCE,
    INSUFFICIENT_EVIDENCE,
    TERMINAL_STATUS
}