FROM docker:29.5.3-cli-alpine3.23@sha256:873de13208aab9c1de73fe984fd45883e01464fcfcc85efa20aa56a9ccfe7aa6

RUN apk add --no-cache python3=3.12.14-r0

ENTRYPOINT ["python3", "/opt/parkio/docker_log_source.py"]
