#!/usr/bin/env bash
# Generate first-party invite-production credentials and store them in Key Vault.
# Third-party/operator values (Slack, MapTiler, email, Expo) are intentionally not
# generated by this script.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
RESOURCE_GROUP="rg-parkio-invite-production-we"
FOUNDATION_DEPLOYMENT="prod-deploy-01a-foundation"
DEPLOYMENT_NAME="prod-deploy-01a-runtime-secrets"
TEMPLATE="$ROOT/infra/azure/invite-production/runtime-secrets.bicep"
CONFIRMATION=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --confirm) CONFIRMATION="${2:-}"; shift 2 ;;
    -h|--help) sed -n '2,4p' "$0"; exit 0 ;;
    *) echo "ERROR: unknown argument '$1'" >&2; exit 2 ;;
  esac
done

if [ "$CONFIRMATION" != "PROD-DEPLOY-01A" ]; then
  echo "ERROR: secret provisioning requires --confirm PROD-DEPLOY-01A." >&2
  exit 2
fi

for tool in az openssl python3; do
  command -v "$tool" >/dev/null 2>&1 || { echo "ERROR: required tool not found: $tool" >&2; exit 2; }
done

AZ_PATH="$(command -v az)"
AZ_TEMPLATE="$TEMPLATE"
if [[ "$AZ_PATH" == /mnt/c/* ]] && command -v wslpath >/dev/null 2>&1; then
  AZ_TEMPLATE="$(wslpath -w "$TEMPLATE")"
fi

az bicep build --file "$AZ_TEMPLATE" --stdout >/dev/null

KEY_VAULT_NAME="$(az deployment group show \
  --name "$FOUNDATION_DEPLOYMENT" \
  --resource-group "$RESOURCE_GROUP" \
  --query properties.outputs.keyVaultName.value \
  --output tsv | tr -d '\r')"
if [ -z "$KEY_VAULT_NAME" ]; then
  echo "ERROR: foundation deployment did not expose a Key Vault name." >&2
  exit 2
fi

TEMP_BASE="${TMPDIR:-/tmp}"
if [[ "$AZ_PATH" == /mnt/c/* ]] && command -v cmd.exe >/dev/null 2>&1 && command -v wslpath >/dev/null 2>&1; then
  WINDOWS_TEMP="$(cmd.exe /d /c 'echo %TEMP%' 2>/dev/null | tr -d '\r')"
  TEMP_BASE="$(wslpath -u "$WINDOWS_TEMP")"
fi
SECURE_TEMP_DIR="$(mktemp -d "$TEMP_BASE/parkio-invite-secrets.XXXXXX")"
chmod 700 "$SECURE_TEMP_DIR"
cleanup() {
  if [ -n "${SECURE_TEMP_DIR:-}" ] && [[ "$SECURE_TEMP_DIR" == "$TEMP_BASE"/parkio-invite-secrets.* ]]; then
    rm -rf -- "$SECURE_TEMP_DIR"
  fi
}
trap cleanup EXIT HUP INT TERM

JWT_PRIVATE_KEY_FILE="$SECURE_TEMP_DIR/jwt-private.pem"
PARAMETERS_FILE="$SECURE_TEMP_DIR/parameters.json"
umask 077
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:3072 -out "$JWT_PRIVATE_KEY_FILE" 2>/dev/null

python3 - "$PARAMETERS_FILE" "$JWT_PRIVATE_KEY_FILE" "$KEY_VAULT_NAME" <<'PY'
import base64
import json
import secrets
import string
import sys
import uuid
from pathlib import Path

output_path = Path(sys.argv[1])
jwt_path = Path(sys.argv[2])
key_vault_name = sys.argv[3]

alphabet = string.ascii_letters + string.digits

def token(length=64):
    return "Aa1!" + "".join(secrets.choice(alphabet) for _ in range(length - 4))

services = [
    "auth", "gateway", "user", "parking", "media", "gamification",
    "notification", "moderation", "analytics", "aivalidation",
]

runtime = {
    "jwt-private-key-pem": jwt_path.read_text(),
    "gateway-internal-secret": token(),
    "waitlist-hash-secret": token(),
    "redis-password": token(48),
    "kafka-cluster-id": base64.urlsafe_b64encode(uuid.uuid4().bytes).decode().rstrip("="),
    "minio-root-password": token(48),
    "grafana-admin-password": token(48),
    "backup-encryption-passphrase": token(80),
}
for service in services:
    runtime[f"postgres-{service}-runtime-password"] = token(48)
    runtime[f"postgres-{service}-migration-password"] = token(48)

document = {
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "keyVaultName": {"value": key_vault_name},
        "runtimeSecrets": {"value": runtime},
    },
}
output_path.write_text(json.dumps(document))
PY

AZ_PARAMETERS_FILE="$PARAMETERS_FILE"
if [[ "$AZ_PATH" == /mnt/c/* ]] && command -v wslpath >/dev/null 2>&1; then
  AZ_PARAMETERS_FILE="$(wslpath -w "$PARAMETERS_FILE")"
fi

echo "Validating generated-secret deployment (values suppressed)..."
az deployment group validate \
  --name "$DEPLOYMENT_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$AZ_TEMPLATE" \
  --parameters "@$AZ_PARAMETERS_FILE" \
  --output none

echo "Writing generated first-party secrets to Key Vault..."
az deployment group create \
  --name "$DEPLOYMENT_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$AZ_TEMPLATE" \
  --parameters "@$AZ_PARAMETERS_FILE" \
  --output none

echo "Generated first-party secret provisioning completed. Values were not printed."
