#!/usr/bin/env bash
#
# Parkio — cleanup of data generated by the real-stack E2E suite.
#
# Removes ONLY data attributable to the seeded test accounts (PARKIO_REAL_*_EMAIL) and/or
# the suite's test-spot address marker. It never touches real user data: every delete is
# scoped to the seeded accounts' auth ids (looked up by their dedicated test emails) or to
# the well-known test address prefix. Run after a real E2E run to keep test stacks tidy.
#
# What it removes (per service DB, database-per-service):
#   parking      : spots owned by the seed accounts OR matching the test address prefix,
#                  plus their verification / status-history / view-log child rows
#   media        : media files owned by the seed accounts, plus their validation results
#                  (NOTE: the MinIO object bytes are not deleted here — see docs)
#   moderation   : reports filed by the seed accounts
#   notification : notifications addressed to the seed accounts
#   auth/user    : the seed ACCOUNTS themselves — only with --accounts
#
# Usage (local Docker — default):
#   export PARKIO_REAL_USER_EMAIL=user@real-e2e.parkio.local
#   # MODERATOR/ADMIN emails optional; include them to clean their data too
#   PARKIO_ENV_FILE=docker/.env ./scripts/cleanup-real-e2e.sh           # data only
#   PARKIO_ENV_FILE=docker/.env ./scripts/cleanup-real-e2e.sh --accounts # also drop accounts
#
# Hosted-beta: SSH to the VPS first, then run with --target hosted-beta (see seed script).
#
# Flags:
#   --target local|hosted-beta|production  Where the containers live (default: local).
#   --accounts                             Also delete the seeded auth users + profiles.
#   --dry-run                              Show what would be deleted; change nothing.
#   -h | --help                            This help.
#
# Safety: production refuses unless PARKIO_CONFIRM_PRODUCTION=I_UNDERSTAND.

set -euo pipefail

TARGET="local"
DELETE_ACCOUNTS="0"
DRY_RUN="0"

while [ $# -gt 0 ]; do
  case "$1" in
    --target) TARGET="${2:-}"; shift 2 ;;
    --target=*) TARGET="${1#*=}"; shift ;;
    --accounts) DELETE_ACCOUNTS="1"; shift ;;
    --dry-run) DRY_RUN="1"; shift ;;
    -h|--help) sed -n '2,40p' "$0"; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

case "$TARGET" in
  local|hosted-beta) ;;
  production)
    if [ "${PARKIO_CONFIRM_PRODUCTION:-}" != "I_UNDERSTAND" ]; then
      echo "REFUSING to delete data against PRODUCTION." >&2
      echo "Set PARKIO_CONFIRM_PRODUCTION=I_UNDERSTAND to override." >&2
      exit 3
    fi
    echo "WARNING: cleaning test data against PRODUCTION (explicitly confirmed)." >&2
    ;;
  *) echo "Invalid --target '$TARGET' (expected local|hosted-beta|production)." >&2; exit 2 ;;
esac

ENV_FILE="${PARKIO_ENV_FILE:-}"
if [ -n "${ENV_FILE}" ] && [ -f "${ENV_FILE}" ]; then
  set -a; # shellcheck disable=SC1090
  . "${ENV_FILE}"; set +a
fi

AUTH_CONTAINER="${PARKIO_AUTH_PG_CONTAINER:-parkio-postgres-auth}"
AUTH_DB_USER="${POSTGRES_AUTH_USER:-parkio_auth}"; AUTH_DB="${POSTGRES_AUTH_DB:-parkio_auth}"
USER_CONTAINER="${PARKIO_USER_PG_CONTAINER:-parkio-postgres-user}"
USER_DB_USER="${POSTGRES_USER_USER:-parkio_user}"; USER_DB="${POSTGRES_USER_DB:-parkio_user}"
PARKING_CONTAINER="parkio-postgres-parking"; PARKING_DB_USER="${POSTGRES_PARKING_USER:-parkio_parking}"; PARKING_DB="${POSTGRES_PARKING_DB:-parkio_parking}"
MEDIA_CONTAINER="parkio-postgres-media"; MEDIA_DB_USER="${POSTGRES_MEDIA_USER:-parkio_media}"; MEDIA_DB="${POSTGRES_MEDIA_DB:-parkio_media}"
MODERATION_CONTAINER="parkio-postgres-moderation"; MODERATION_DB_USER="${POSTGRES_MODERATION_USER:-parkio_moderation}"; MODERATION_DB="${POSTGRES_MODERATION_DB:-parkio_moderation}"
NOTIFICATION_CONTAINER="parkio-postgres-notification"; NOTIFICATION_DB_USER="${POSTGRES_NOTIFICATION_USER:-parkio_notification}"; NOTIFICATION_DB="${POSTGRES_NOTIFICATION_DB:-parkio_notification}"

ADDRESS_PREFIX="${PARKIO_REAL_E2E_ADDRESS_PREFIX:-Q5 Real Stack Test Spot%}"

lc() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }

# Collect the seed emails that are actually configured.
EMAILS=()
for v in PARKIO_REAL_USER_EMAIL PARKIO_REAL_MODERATOR_EMAIL PARKIO_REAL_ADMIN_EMAIL; do
  val="${!v:-}"
  [ -n "$val" ] && EMAILS+=("$(lc "$val")")
done
if [ "${#EMAILS[@]}" -eq 0 ]; then
  echo "ERROR: set at least PARKIO_REAL_USER_EMAIL so cleanup can scope to the test accounts." >&2
  exit 5
fi

require_container() { docker inspect "$1" >/dev/null 2>&1 || { echo "ERROR: container '$1' not found (is the $TARGET stack up?)" >&2; exit 4; }; }
psql_db() { local c="$1" u="$2" d="$3"; shift 3; docker exec -i "$c" psql -v ON_ERROR_STOP=1 -X -U "$u" -d "$d" "$@"; }

require_container "$AUTH_CONTAINER"

# Build a Postgres uuid[] literal of the seeded accounts' auth ids (authoritative lookup).
emails_pg="{$(IFS=,; echo "${EMAILS[*]}")}"
# psql interpolates :vars only from stdin/-f, never from a -c SQL string, so pipe the
# lookup in (the run_step helper already relies on this). -v still binds :'emails'.
ids_csv="$(printf '%s' "SELECT string_agg(id::text, ',') FROM auth_users WHERE email = ANY(:'emails'::text[])" \
  | psql_db "$AUTH_CONTAINER" "$AUTH_DB_USER" "$AUTH_DB" -tAq -v emails="$emails_pg")"
ids_csv="$(printf '%s' "$ids_csv" | tr -d '[:space:]')"
ids_pg="{${ids_csv}}"   # may be {} if no accounts exist yet

echo "Cleanup real-stack E2E data (target=${TARGET}, dry_run=${DRY_RUN}, accounts=${DELETE_ACCOUNTS})"
echo "  scope: emails=[${EMAILS[*]}] address_prefix='${ADDRESS_PREFIX}'"
echo "  seed auth ids: ${ids_csv:-<none found>}"

# count|delete helper: runs SELECT count in dry-run, otherwise the DELETE returning row count.
# SQL is fed on stdin (not -c) so multi-statement deletes run in one session — the parking
# TEMP TABLE must persist across the child-row deletes within its BEGIN/COMMIT block.
run_step() { # <label> <container> <user> <db> <count_sql> <delete_sql>
  local label="$1" c="$2" u="$3" d="$4" csql="$5" dsql="$6"
  if ! docker inspect "$c" >/dev/null 2>&1; then echo "  skip ${label}: container '$c' not found"; return; fi
  if [ "$DRY_RUN" = "1" ]; then
    local n; n="$(printf '%s' "$csql" | psql_db "$c" "$u" "$d" -tAq -v ids="$ids_pg" -v prefix="$ADDRESS_PREFIX" -v emails="$emails_pg")"
    echo "  would delete ${label}: ${n}"
  else
    printf '%s' "$dsql" | psql_db "$c" "$u" "$d" -v ids="$ids_pg" -v prefix="$ADDRESS_PREFIX" -v emails="$emails_pg" \
      | sed "s/^/  ${label}: /"
  fi
}

# --- parking: spots (+ children) by owner or test address marker ---
PARKING_DELETE="$(cat <<'SQL'
BEGIN;
CREATE TEMP TABLE _t ON COMMIT DROP AS
  SELECT id FROM parking_spots
  WHERE owner_user_id = ANY(:'ids'::uuid[]) OR address_text LIKE :'prefix';
DELETE FROM parking_spot_verifications  WHERE spot_id IN (SELECT id FROM _t);
DELETE FROM parking_spot_status_history WHERE spot_id IN (SELECT id FROM _t);
DELETE FROM parking_spot_view_logs      WHERE spot_id IN (SELECT id FROM _t);
WITH d AS (DELETE FROM parking_spots WHERE id IN (SELECT id FROM _t) RETURNING 1)
SELECT 'spots deleted=' || count(*) FROM d;
COMMIT;
SQL
)"
PARKING_COUNT="SELECT count(*) FROM parking_spots WHERE owner_user_id = ANY(:'ids'::uuid[]) OR address_text LIKE :'prefix'"
run_step "parking" "$PARKING_CONTAINER" "$PARKING_DB_USER" "$PARKING_DB" "$PARKING_COUNT" "$PARKING_DELETE"

# --- media: files (+ validation results) owned by the seed accounts ---
MEDIA_DELETE="$(cat <<'SQL'
DELETE FROM media_validation_results WHERE media_id IN (SELECT id FROM media_files WHERE owner_user_id = ANY(:'ids'::uuid[]));
WITH d AS (DELETE FROM media_files WHERE owner_user_id = ANY(:'ids'::uuid[]) RETURNING 1)
SELECT 'media files deleted=' || count(*) FROM d;
SQL
)"
MEDIA_COUNT="SELECT count(*) FROM media_files WHERE owner_user_id = ANY(:'ids'::uuid[])"
run_step "media" "$MEDIA_CONTAINER" "$MEDIA_DB_USER" "$MEDIA_DB" "$MEDIA_COUNT" "$MEDIA_DELETE"

# --- moderation: reports filed by the seed accounts ---
MOD_DELETE="WITH d AS (DELETE FROM user_reports WHERE reporter_user_id = ANY(:'ids'::uuid[]) RETURNING 1) SELECT 'reports deleted=' || count(*) FROM d"
MOD_COUNT="SELECT count(*) FROM user_reports WHERE reporter_user_id = ANY(:'ids'::uuid[])"
run_step "moderation" "$MODERATION_CONTAINER" "$MODERATION_DB_USER" "$MODERATION_DB" "$MOD_COUNT" "$MOD_DELETE"

# --- notification: notifications addressed to the seed accounts ---
NOTIF_DELETE="WITH d AS (DELETE FROM notifications WHERE user_id = ANY(:'ids'::uuid[]) RETURNING 1) SELECT 'notifications deleted=' || count(*) FROM d"
NOTIF_COUNT="SELECT count(*) FROM notifications WHERE user_id = ANY(:'ids'::uuid[])"
run_step "notification" "$NOTIFICATION_CONTAINER" "$NOTIFICATION_DB_USER" "$NOTIFICATION_DB" "$NOTIF_COUNT" "$NOTIF_DELETE"

# --- optionally drop the seed accounts (auth cascades roles/tokens; user cascades trust/prefs) ---
if [ "$DELETE_ACCOUNTS" = "1" ]; then
  USER_DELETE="WITH d AS (DELETE FROM user_profiles WHERE auth_user_id = ANY(:'ids'::uuid[]) RETURNING 1) SELECT 'profiles deleted=' || count(*) FROM d"
  USER_COUNT="SELECT count(*) FROM user_profiles WHERE auth_user_id = ANY(:'ids'::uuid[])"
  run_step "user-profiles" "$USER_CONTAINER" "$USER_DB_USER" "$USER_DB" "$USER_COUNT" "$USER_DELETE"

  AUTH_DELETE="WITH d AS (DELETE FROM auth_users WHERE email = ANY(:'emails'::text[]) RETURNING 1) SELECT 'auth users deleted=' || count(*) FROM d"
  AUTH_COUNT="SELECT count(*) FROM auth_users WHERE email = ANY(:'emails'::text[])"
  run_step "auth-users" "$AUTH_CONTAINER" "$AUTH_DB_USER" "$AUTH_DB" "$AUTH_COUNT" "$AUTH_DELETE"
fi

echo "Done.${DRY_RUN:+}"
[ "$DRY_RUN" = "1" ] && echo "(dry-run: nothing was changed)"
exit 0
