import { describe, expectTypeOf, it } from 'vitest';
import type { z, ZodTypeAny } from 'zod';
import type {
  AdminAuditEvent,
  AdminAuditListParams,
  AdminDashboard,
  AdminPage,
  AdminReasonBody,
  AdminRoleChangeBody,
  AdminSecuritySummary,
  AdminSession,
  AdminUserDetail,
  AdminUserListParams,
  AdminUserSummary,
  AiValidationResult,
  AnalyticsMetric,
  AnalyticsOverview,
  ApiError,
  AppNotification,
  AuthResponse,
  ChangePasswordRequest,
  ClaimedRegion,
  CommunityClaimResponse,
  CreateAppealRequest,
  CreateReportRequest,
  CreateSpotRequest,
  DailyAnalytics,
  Destination,
  DeviceToken,
  FieldError,
  ForgotPasswordRequest,
  GamificationAccessPolicy,
  GamificationProgress,
  GeocodeResult,
  GeocodeSearchResponse,
  LeaderboardEntry,
  LevelRule,
  LevelStanding,
  LoginRequest,
  LogoutRequest,
  MediaAccessUrl,
  MediaMetadata,
  MobileTokenRequest,
  ModerationAppeal,
  ModerationCase,
  ModerationReport,
  NearbySearchParams,
  ParkingAnalytics,
  ParkingSessionHistoryParams,
  ParkingSessionHistoryResponse,
  ParkingSessionResponse,
  PlaceIdentity,
  PointTransactionEntry,
  PointsSummary,
  Profile,
  PublicProfile,
  PublicSpotResponse,
  RefreshTokenRequest,
  RegisterDeviceTokenRequest,
  RegisterRequest,
  ResendVerificationRequest,
  ResetPasswordRequest,
  ResolveAppealRequest,
  ResolveCaseRequest,
  SavedPlace,
  SavedPlaceListResponse,
  FavouriteDestination,
  FavouriteDestinationListResponse,
  FavouriteParking,
  FavouriteParkingListResponse,
  FavouriteParkingStatusResponse,
  RecommendationRequest,
  RecommendationResponse,
  ParkingCandidate,
  SmartReturnSettings,
  SmartReturnTodayRequest,
  SpotMediaAccessUrlResponse,
  SpotResponse,
  StartParkingSessionRequest,
  SubmitWaitlistRequest,
  UpdateFavouriteDestinationRequest,
  UpdatePreferenceRequest,
  UpdateProfileRequest,
  UpdateSmartReturnSettingsRequest,
  UploadMediaResponse,
  UpsertSavedPlaceRequest,
  UpsertVehicleRequest,
  User,
  UserAnalytics,
  UserPreference,
  UserStats,
  VehicleProfile,
  VerifyEmailRequest,
  VerifySpotRequest,
  WaitlistAcceptedResponse,
  CreateCustomSavedPlaceRequest,
  CreateFavouriteDestinationRequest,
  CreateFavouriteParkingRequest,
} from '@parkio/types';
import { apiErrorSchema, fieldErrorSchema } from '../api-error';
import {
  adminAuditEventResponseSchema,
  adminAuditListParamsSchema,
  adminAuditPageResponseSchema,
  adminDashboardResponseSchema,
  adminReasonBodySchema,
  adminRoleChangeBodySchema,
  adminSecuritySummaryResponseSchema,
  adminSessionResponseSchema,
  adminUserDetailResponseSchema,
  adminUserListParamsSchema,
  adminUserPageResponseSchema,
  adminUserSummaryResponseSchema,
} from './admin';
import {
  analyticsMetricResponseSchema,
  analyticsOverviewResponseSchema,
  dailyAnalyticsResponseSchema,
  parkingAnalyticsResponseSchema,
  userAnalyticsResponseSchema,
} from './analytics';
import {
  authResponseSchema,
  changePasswordRequestSchema,
  forgotPasswordRequestSchema,
  loginRequestSchema,
  logoutRequestSchema,
  mobileTokenRequestSchema,
  refreshTokenRequestSchema,
  registerRequestSchema,
  resendVerificationRequestSchema,
  resetPasswordRequestSchema,
  userResponseSchema,
  verifyEmailRequestSchema,
} from './auth';
import {
  gamificationAccessPolicyResponseSchema,
  gamificationProgressResponseSchema,
  leaderboardEntryResponseSchema,
  levelRuleResponseSchema,
  levelStandingResponseSchema,
  pointTransactionEntryResponseSchema,
  pointsSummaryResponseSchema,
} from './gamification';
import { geocodeResultResponseSchema, geocodeSearchResponseSchema } from './geocoding';
import { destinationSchema, placeIdentitySchema } from './destination';
import {
  createCustomSavedPlaceRequestSchema,
  savedPlaceListResponseSchema,
  savedPlaceSchema,
  upsertSavedPlaceRequestSchema,
} from './saved-place';
import {
  createFavouriteDestinationRequestSchema,
  createFavouriteParkingRequestSchema,
  favouriteDestinationListResponseSchema,
  favouriteDestinationSchema,
  favouriteParkingListResponseSchema,
  favouriteParkingSchema,
  favouriteParkingStatusResponseSchema,
  updateFavouriteDestinationRequestSchema,
} from './favourite';
import {
  parkingCandidateSchema,
  recommendationRequestSchema,
  recommendationResponseSchema,
} from './recommendation';
import {
  aiValidationResultResponseSchema,
  claimedRegionResponseSchema,
  mediaAccessUrlResponseSchema,
  mediaMetadataResponseSchema,
  uploadMediaResponseSchema,
} from './media';
import {
  createAppealRequestSchema,
  createReportRequestSchema,
  moderationAppealResponseSchema,
  moderationCaseResponseSchema,
  moderationReportResponseSchema,
  resolveAppealRequestSchema,
  resolveCaseRequestSchema,
} from './moderation';
import {
  deviceTokenResponseSchema,
  notificationResponseSchema,
  registerDeviceTokenRequestSchema,
} from './notification';
import {
  communityClaimResponseSchema,
  createSpotRequestSchema,
  nearbySearchParamsContractSchema,
  parkingSessionHistoryParamsSchema,
  parkingSessionHistoryResponseSchema,
  parkingSessionResponseSchema,
  publicSpotResponseSchema,
  spotMediaAccessUrlResponseSchema,
  spotResponseSchema,
  startParkingSessionRequestSchema,
  verifySpotRequestSchema,
} from './parking';
import {
  profileResponseSchema,
  publicProfileResponseSchema,
  smartReturnSettingsResponseSchema,
  smartReturnTodayRequestSchema,
  updatePreferenceRequestSchema,
  updateProfileRequestSchema,
  updateSmartReturnSettingsRequestSchema,
  upsertVehicleRequestSchema,
  userPreferenceResponseSchema,
  userStatsResponseSchema,
  vehicleProfileResponseSchema,
} from './user';
import { submitWaitlistRequestSchema, waitlistAcceptedResponseSchema } from './waitlist';

type Equal<Left, Right> =
  (<Value>() => Value extends Left ? 1 : 2) extends <Value>() => Value extends Right ? 1 : 2
    ? (<Value>() => Value extends Right ? 1 : 2) extends <Value>() => Value extends Left ? 1 : 2
      ? true
      : false
    : false;

type SchemaMatches<Schema extends ZodTypeAny, Model> =
  Equal<z.input<Schema>, Model> extends true
    ? Equal<z.output<Schema>, Model> extends true
      ? true
      : false
    : false;

type Assert<Condition extends true> = Condition;

type ContractSchemaAssertions = [
  Assert<SchemaMatches<typeof fieldErrorSchema, FieldError>>,
  Assert<SchemaMatches<typeof apiErrorSchema, ApiError>>,
  Assert<SchemaMatches<typeof loginRequestSchema, LoginRequest>>,
  Assert<SchemaMatches<typeof registerRequestSchema, RegisterRequest>>,
  Assert<SchemaMatches<typeof verifyEmailRequestSchema, VerifyEmailRequest>>,
  Assert<SchemaMatches<typeof resendVerificationRequestSchema, ResendVerificationRequest>>,
  Assert<SchemaMatches<typeof forgotPasswordRequestSchema, ForgotPasswordRequest>>,
  Assert<SchemaMatches<typeof resetPasswordRequestSchema, ResetPasswordRequest>>,
  Assert<SchemaMatches<typeof changePasswordRequestSchema, ChangePasswordRequest>>,
  Assert<SchemaMatches<typeof mobileTokenRequestSchema, MobileTokenRequest>>,
  Assert<SchemaMatches<typeof refreshTokenRequestSchema, RefreshTokenRequest>>,
  Assert<SchemaMatches<typeof logoutRequestSchema, LogoutRequest>>,
  Assert<SchemaMatches<typeof userResponseSchema, User>>,
  Assert<SchemaMatches<typeof authResponseSchema, AuthResponse>>,
  Assert<SchemaMatches<typeof nearbySearchParamsContractSchema, NearbySearchParams>>,
  Assert<SchemaMatches<typeof createSpotRequestSchema, CreateSpotRequest>>,
  Assert<SchemaMatches<typeof verifySpotRequestSchema, VerifySpotRequest>>,
  Assert<SchemaMatches<typeof startParkingSessionRequestSchema, StartParkingSessionRequest>>,
  Assert<SchemaMatches<typeof parkingSessionHistoryParamsSchema, ParkingSessionHistoryParams>>,
  Assert<SchemaMatches<typeof publicSpotResponseSchema, PublicSpotResponse>>,
  Assert<SchemaMatches<typeof spotResponseSchema, SpotResponse>>,
  Assert<SchemaMatches<typeof spotMediaAccessUrlResponseSchema, SpotMediaAccessUrlResponse>>,
  Assert<SchemaMatches<typeof parkingSessionResponseSchema, ParkingSessionResponse>>,
  Assert<SchemaMatches<typeof parkingSessionHistoryResponseSchema, ParkingSessionHistoryResponse>>,
  Assert<SchemaMatches<typeof communityClaimResponseSchema, CommunityClaimResponse>>,
  Assert<SchemaMatches<typeof updateProfileRequestSchema, UpdateProfileRequest>>,
  Assert<SchemaMatches<typeof updatePreferenceRequestSchema, UpdatePreferenceRequest>>,
  Assert<SchemaMatches<typeof updateSmartReturnSettingsRequestSchema, UpdateSmartReturnSettingsRequest>>,
  Assert<SchemaMatches<typeof smartReturnTodayRequestSchema, SmartReturnTodayRequest>>,
  Assert<SchemaMatches<typeof upsertVehicleRequestSchema, UpsertVehicleRequest>>,
  Assert<SchemaMatches<typeof profileResponseSchema, Profile>>,
  Assert<SchemaMatches<typeof userPreferenceResponseSchema, UserPreference>>,
  Assert<SchemaMatches<typeof smartReturnSettingsResponseSchema, SmartReturnSettings>>,
  Assert<SchemaMatches<typeof vehicleProfileResponseSchema, VehicleProfile>>,
  Assert<SchemaMatches<typeof userStatsResponseSchema, UserStats>>,
  Assert<SchemaMatches<typeof publicProfileResponseSchema, PublicProfile>>,
  Assert<SchemaMatches<typeof registerDeviceTokenRequestSchema, RegisterDeviceTokenRequest>>,
  Assert<SchemaMatches<typeof notificationResponseSchema, AppNotification>>,
  Assert<SchemaMatches<typeof deviceTokenResponseSchema, DeviceToken>>,
  Assert<SchemaMatches<typeof claimedRegionResponseSchema, ClaimedRegion>>,
  Assert<SchemaMatches<typeof uploadMediaResponseSchema, UploadMediaResponse>>,
  Assert<SchemaMatches<typeof mediaAccessUrlResponseSchema, MediaAccessUrl>>,
  Assert<SchemaMatches<typeof mediaMetadataResponseSchema, MediaMetadata>>,
  Assert<SchemaMatches<typeof aiValidationResultResponseSchema, AiValidationResult>>,
  Assert<SchemaMatches<typeof createReportRequestSchema, CreateReportRequest>>,
  Assert<SchemaMatches<typeof createAppealRequestSchema, CreateAppealRequest>>,
  Assert<SchemaMatches<typeof resolveCaseRequestSchema, ResolveCaseRequest>>,
  Assert<SchemaMatches<typeof resolveAppealRequestSchema, ResolveAppealRequest>>,
  Assert<SchemaMatches<typeof moderationReportResponseSchema, ModerationReport>>,
  Assert<SchemaMatches<typeof moderationAppealResponseSchema, ModerationAppeal>>,
  Assert<SchemaMatches<typeof moderationCaseResponseSchema, ModerationCase>>,
  Assert<SchemaMatches<typeof analyticsOverviewResponseSchema, AnalyticsOverview>>,
  Assert<SchemaMatches<typeof dailyAnalyticsResponseSchema, DailyAnalytics>>,
  Assert<SchemaMatches<typeof userAnalyticsResponseSchema, UserAnalytics>>,
  Assert<SchemaMatches<typeof parkingAnalyticsResponseSchema, ParkingAnalytics>>,
  Assert<SchemaMatches<typeof analyticsMetricResponseSchema, AnalyticsMetric>>,
  Assert<SchemaMatches<typeof geocodeResultResponseSchema, GeocodeResult>>,
  Assert<SchemaMatches<typeof geocodeSearchResponseSchema, GeocodeSearchResponse>>,
  Assert<SchemaMatches<typeof placeIdentitySchema, PlaceIdentity>>,
  Assert<SchemaMatches<typeof destinationSchema, Destination>>,
  Assert<SchemaMatches<typeof savedPlaceSchema, SavedPlace>>,
  Assert<SchemaMatches<typeof savedPlaceListResponseSchema, SavedPlaceListResponse>>,
  Assert<SchemaMatches<typeof upsertSavedPlaceRequestSchema, UpsertSavedPlaceRequest>>,
  Assert<SchemaMatches<typeof createCustomSavedPlaceRequestSchema, CreateCustomSavedPlaceRequest>>,
  Assert<SchemaMatches<typeof favouriteParkingSchema, FavouriteParking>>,
  Assert<SchemaMatches<typeof favouriteParkingListResponseSchema, FavouriteParkingListResponse>>,
  Assert<SchemaMatches<typeof createFavouriteParkingRequestSchema, CreateFavouriteParkingRequest>>,
  Assert<SchemaMatches<typeof favouriteParkingStatusResponseSchema, FavouriteParkingStatusResponse>>,
  Assert<SchemaMatches<typeof favouriteDestinationSchema, FavouriteDestination>>,
  Assert<SchemaMatches<typeof favouriteDestinationListResponseSchema, FavouriteDestinationListResponse>>,
  Assert<SchemaMatches<typeof createFavouriteDestinationRequestSchema, CreateFavouriteDestinationRequest>>,
  Assert<SchemaMatches<typeof updateFavouriteDestinationRequestSchema, UpdateFavouriteDestinationRequest>>,
  Assert<SchemaMatches<typeof recommendationRequestSchema, RecommendationRequest>>,
  Assert<SchemaMatches<typeof recommendationResponseSchema, RecommendationResponse>>,
  Assert<SchemaMatches<typeof parkingCandidateSchema, ParkingCandidate>>,
  Assert<SchemaMatches<typeof gamificationProgressResponseSchema, GamificationProgress>>,
  Assert<SchemaMatches<typeof pointTransactionEntryResponseSchema, PointTransactionEntry>>,
  Assert<SchemaMatches<typeof pointsSummaryResponseSchema, PointsSummary>>,
  Assert<SchemaMatches<typeof levelStandingResponseSchema, LevelStanding>>,
  Assert<SchemaMatches<typeof gamificationAccessPolicyResponseSchema, GamificationAccessPolicy>>,
  Assert<SchemaMatches<typeof levelRuleResponseSchema, LevelRule>>,
  Assert<SchemaMatches<typeof leaderboardEntryResponseSchema, LeaderboardEntry>>,
  Assert<SchemaMatches<typeof adminUserListParamsSchema, AdminUserListParams>>,
  Assert<SchemaMatches<typeof adminAuditListParamsSchema, AdminAuditListParams>>,
  Assert<SchemaMatches<typeof adminReasonBodySchema, AdminReasonBody>>,
  Assert<SchemaMatches<typeof adminRoleChangeBodySchema, AdminRoleChangeBody>>,
  Assert<SchemaMatches<typeof adminDashboardResponseSchema, AdminDashboard>>,
  Assert<SchemaMatches<typeof adminUserSummaryResponseSchema, AdminUserSummary>>,
  Assert<SchemaMatches<typeof adminSessionResponseSchema, AdminSession>>,
  Assert<SchemaMatches<typeof adminAuditEventResponseSchema, AdminAuditEvent>>,
  Assert<SchemaMatches<typeof adminUserDetailResponseSchema, AdminUserDetail>>,
  Assert<SchemaMatches<typeof adminUserPageResponseSchema, AdminPage<AdminUserSummary>>>,
  Assert<SchemaMatches<typeof adminAuditPageResponseSchema, AdminPage<AdminAuditEvent>>>,
  Assert<SchemaMatches<typeof adminSecuritySummaryResponseSchema, AdminSecuritySummary>>,
  Assert<SchemaMatches<typeof submitWaitlistRequestSchema, SubmitWaitlistRequest>>,
  Assert<SchemaMatches<typeof waitlistAcceptedResponseSchema, WaitlistAcceptedResponse>>,
];

describe('contract type consistency', () => {
  it('keeps every model identical to both validator input and output', () => {
    expectTypeOf<ContractSchemaAssertions>().toMatchTypeOf<readonly true[]>();
  });
});
