package com.parkio.media.application.port;

/** Decodes uploaded images and returns safe server-generated bytes for storage. */
public interface ImageNormalizer {

    NormalizedImage normalize(byte[] content, String detectedContentType);

    record NormalizedImage(byte[] content, String contentType) {
    }
}
