package com.parkio.parking.exposure;

public enum ExposureEligibility {
    ELIGIBLE,
    INELIGIBLE_NOT_PUBLISHED,
    INELIGIBLE_TERMINAL_STATUS,
    INELIGIBLE_EXPIRED,
    INELIGIBLE_LEGAL,
    INELIGIBLE_VEHICLE_MISMATCH,
    INELIGIBLE_AVAILABILITY,
    INSUFFICIENT_EVIDENCE,
    POLICY_UNSUPPORTED
}
